# This is a basic workflow to help you get started with Actions

name: Refresh Repo info

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh_readme:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: frdmn/age-calculator-action@v1.1
        id: birthday
        with:
          date: '1995-06-01'

      - uses: frdmn/age-calculator-action@v1.1
        id: start_work
        with:
          date: '2017-07-01'

      - name: Update birthday
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '<span id="birthday">\d*<\/span>'
          replace: <span id="birthday">${{ steps.birthday.outputs.age }}</span>
          regex: true
          include: "README.md"

      - name: Update start work
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '<span id="start_work">\d*<\/span>'
          replace: <span id="start_work">${{ steps.start_work.outputs.age }}</span>
          regex: true
          include: "README.md"

      - name: Test file
        run: cat README.md
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Push changes
        with:
          commit_message: Refresh README.md
          
      
